services:
  - type: web
    name: skd-cloud-security-api
    env: python
    region: singapore
    plan: free
    branch: main
    rootDir: server
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SERVER_SECRET_SALT
        generateValue: true
